name: Deployment pipeline

on:
  push:
    branches:
      # note that your "main" branch might be called main instead of master
      - master
  pull_request:
    branches:
      - master
    # note that your "main" branch might be called main instead of master
    types: [opened, synchronize]

# GitHub secret for deploying to fly.io
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  install_and_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: npm install
        run: npm install
      - name: lint
        run: npm run lint
      - name: build
        run: npm run build
  deploy:
      # Wait for build
      needs: [install_and_build]
      name: Deploy app
      runs-on: ubuntu-latest
      # If the event is push, and the commit messaged DON'T contain '#skip'
      if: ${{ (github.event_name == 'push' && !contains(join(github.event.commits.*.message), '#skip')) }}
      steps:
        - uses: actions/checkout@v3
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - run: flyctl deploy --remote-only